name: Fork Sync2

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every minute
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fork Sync
        uses: zwping/fork-sync@v1.6.5
        with:
          owner: NVCLong
          token: ${{ secrets.SYNCFORK_TOKEN }}
          head: master # optional, default is master
          base: master # optional, default is master
          merge_method: merge # optional, default is merge
          pr_title: 'Fork Sync: Update from parent repository'
          # optional, default is 'Fork Sync: Update from parent repository'
          pr_message: '' # optional
          ignore_fail: false # optional
          auto_approve: false # optional
          auto_merge: true # optional, default is true
          retries: 4 # optional, default is 4
          retry_after: 30 # optional, default is 60
