name: Fork Sync

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fork Sync
      uses: tgymnich/fork-sync@v1.2.1
      with:
        owner: thanhduy1706  # Your GitHub username
        github_token: ${{ secrets.SYNCFORK_TOKEN }}
        head: master
        base: master
        merge_method: merge
        pr_title: Fork Sync
        pr_message: Automatically sync fork with upstream repository
        ignore_fail: true
